// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookCardController from "./book_card_controller"
application.register("book-card", BookCardController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import MessagePartialController from "./message_partial_controller"
application.register("message-partial", MessagePartialController)

import SearchController from "./search_controller"
application.register("search", SearchController)
