// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessagePartialController from "./message_partial_controller"
application.register("message-partial", MessagePartialController)

import SearchController from "./search_controller"
application.register("search", SearchController)
